### PR TITLE
update phplib to 5.6 to install ganglia

### PR DESCRIPTION
**Pull request by jeffusan**

### CODE REVIEW

**Comment by shivaram** [comment]
@zhaozhang Can you test this PR and see if it fixes ganglia for you ?

**Comment by zhaozhang** [comment]
This PR solved the ganglia start up issue.

**Comment by shivaram** [comment]
@jeffusan Could you revert this redis changes from this PR and only have the httpd conf change ?

**Comment by jeffusan** [comment]
I added the redis configuration inadvertently. I will close this and resubmit.

**Pull request closed without merging**
