### PR TITLE
Move spark-ec2 script from Spark.

### PR DESCRIPTION
**Pull request by rxin**
This pull request moves spark-ec2 and spark_ec2.py from Spark.

### CODE REVIEW

**Comment by rxin** [comment]
cc @shivaram

**Comment by shivaram** [comment]
You also need to move the deploy.generic dir tree from https://github.com/apache/spark/tree/master/ec2/deploy.generic/root/spark-ec2

**Comment by shivaram** [comment]
Thanks - Looks fine. I'll need to test this locally to make sure we haven't broken anything. 

cc @nchammas

**Comment by nchammas** [comment]
Since we're also [removing the docs](https://github.com/apache/spark/pull/10673/files#diff-c05fbf957d7b782ae9e246898f9f207a) from the Spark repo, shouldn't we add those here as well?

**Comment by rxin** [comment]
We should. Do you want to submit a pr?

**Comment by nchammas** [comment]
Sure, I can help with that.

@shivaram - How do we want to host the docs here? Using [GitHub Pages](https://pages.github.com/), perhaps?

@rxin - Depending on what we end up doing, we might ask you (or INFRA?) to setup a redirect from the old spark-ec2 doc page to the new location, because I think that's currently set to 404 when Spark 2.0 is released.

**Comment by rxin** [comment]
Sounds good. I think those are just part of the normal spark doc -- so if you submit a pull request against Spark's doc folder, I can merge it.

**Comment by shivaram** [comment]
Yeah github pages would be cool. And I think the redirect only needs a change to the markdown file in the spark docs repo.

**Comment by ooq** [comment]
Anyone working on closing this? Currently none of the latest code of apache/spark and amplab/spark-ec2 contains the script to launch spark on ec2.

**Comment by nchammas** [comment]
@shivaram - Anything blocking us from merging this PR in? I think the GitHub pages stuff can come in a separate PR.

**Comment by shivaram** [comment]
I just wanted to test this with a couple of clusters to see if the variables were getting propagated correctly. @nchammas @ooq did either of you try to run this and see if it works without any issues ?

**Comment by ooq** [comment]
@shivaram I didn't check this pr out. But if these files are copied directly from spark-1.5, they should work standalone.

**Comment by shivaram** [comment]
The only thing I was worried about is relative paths for the `ec2-variables.sh` file. I can merge this now and we can fix issues in follow up PRs -- @ooq will you be able to test this out after I merge ?

**Comment by ooq** [comment]
Sure, I can try that.

**Comment by ooq** [comment]
Just tried. It works except this version seems to be from 1.6, so the
default spark version is 1.6.0.

**Comment by shivaram** [comment]
Yeah the latest release is 1.6.0 so I think that is expected behavior ?

**Comment by ooq** [comment]
I guess the only problem is that the default branch name is "branch-1.5".

**Comment by shivaram** [comment]
Ah I see. I will create a new `branch-1.6` and make that the default. I guess also need to update the default version in this branch to 1.5

**Comment by shivaram** [comment]
I'll just forked a new `branch-1.6` and set that as default.

**Pull request merged**
