### PR TITLE
Add Spark 2.0.1 to valid spark versions.

### PR DESCRIPTION
**Pull request by lagerspetz**
Added the Spark 2.0.1 release to valid spark versions.
Why is 1.6.2 not in the valid versions in the 2.0 branch?

### CODE REVIEW

**Comment by shivaram** [comment]
Can you also add 1.6.2 -- Its just something that was missed out.

**Comment by lagerspetz** [comment]
Ok, 1.6.2 is in too. I wondered if you want to keep those commits in the 1.6 branch, so I didn't add it at first.

**Comment by shivaram** [comment]
Thanks - The changes are usually inclusive as we go back version numbers. i.e. branch-2.0 should have all of 1.6 etc.  Looking at the file we also need to add 1.6.1 I guess ?

**Comment by shivaram** [comment]
Alright i'm going to merge this PR to branch-2.0. @lagerspetz will be great if you can open a follow up PR to fix up 1.6.1

**Pull request merged**
