### PR TITLE
BUG: Add explicit exports to fix private IP submission.

### LINKED ISSUE #2: Submission scripts are broken on ec2 clusters started with spark-ec2 with private IP's
See [this issue in JIRA](https://issues.apache.org/jira/browse/SPARK-9884).  Fix coming shortly.  @tkunicki

### PR DESCRIPTION
**Pull request by mdagost**
Fixes #2 and https://issues.apache.org/jira/browse/SPARK-9884.

### CODE REVIEW

**Comment by shivaram** [comment]
Hmm I have no idea why this should work relative to existing code, but I don't mind it in case this fixes your issue (one way to debug the existing issue might be to add `set -x` to the top of the file). 
@tkunicki is it possible for you check if this change affects your existing setups ?

**Comment by mdagost** [comment]
@shivaram @tkunicki Here are some simple scripts to mimic the call chain.  This identifies that the problem is the `set -e` line at the top of `bin/spark-class`:

`test_wrap2.sh` <=> `bin/spark-submit`

```
#!/usr/bin/env bash

${HOME}/test_wrap1.sh
```

`test_wrap1.sh` <=> `bin/spark-class`

```
#!/usr/bin/env bash
set -e

set -a
. "test.sh"
set +a
```

`test.sh` <=> `conf/load-spark-env.sh`

```
#!/usr/bin/env bash

BLAH=`wget -q -O - http://169.254.169.254/latest/meta-data/public-hostname`
echo $BLAH
echo "finished..."
```

With the `set -e`, this fails silently in the same way.  Without it, it works.  Same thing happens if I get rid of `set -e` in `bin/spark-class`.

From `help set`:

```
 -e  Exit immediately if a command exits with a non-zero status.
```

I at least feel better having tracked this down all the way now :)  Question is whether we want to stay with my fix or turn off that `set -e`.  I leave it to you guys...

And actually, now that I look, it looks like this bug was transient.  Shit.  This commit removed the `set -e` and it's no longer on master:

https://github.com/apache/spark/commit/700312e12f9588f01a592d6eac7bff7eb366ac8f

So I _think_ that we can just close this issue and ignore this PR?

**Comment by shivaram** [comment]
@mdagost That is a great test case ! Thanks for tracking this down. I think the right fix here is not fail the assignment if `wget` fails, so we make the command 

```
SPARK_PUBLIC_DNS =`wget -q -O - http://169.254.169.254/latest/meta-data/public-hostname || true`
```

I think the `if` clause that follows should still work -- Could you test this out and let me know if it works ?

**Comment by tkunicki** [comment]
We could also get rid of the `if` and use:

```
export SPARK_PUBLIC_DNS=`
wget -q -O - http://169.254.169.254/latest/meta-data/public-hostname ||\
wget -q -O - http://169.254.169.254/latest/meta-data/local-ipv4`
```

**Comment by shivaram** [comment]
@mdagost any luck with this ?

**Comment by mdagost** [comment]
@shivaram @tkunicki Either one of those two suggestions works for me.

**Comment by shivaram** [comment]
I'd say lets go with @tkunicki 's suggestion as that is simpler

**Comment by mdagost** [comment]
Okay @shivaram .  That's in there now.

**Comment by shivaram** [comment]
LGTM. And just to check this does fix the original problem you had right ?

**Comment by mdagost** [comment]
Yep!  I just tested it on a freshly booted 1.4.1 cluster.

**Comment by shivaram** [comment]
Cool. Thanks merging this

**Comment by shivaram** [comment]
BTW could you open another PR against branch-1.4 ? Otherwise this will only get picked up in 1.5

**Pull request merged**
